// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewAuthor struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type NewPost struct {
	Title    string `json:"title"`
	AuthorID string `json:"authorID"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
